# This is a basic workflow to help you get started with Actions

name: Hexo-Deploy-CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ hexo ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: hexo

    - name: Setup Node.js Env
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: hexo/package-lock.json

    - name: Config SSH Key & Git
      env:
        SSH_KEY: ${{ secrets.hexo_deploy_ssh_key }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'wangluyuan'
        git config --global user.email 'mail@luyuan.wang'
    
    - name: Setup Hexo Env
      run: |
        npm i -g hexo-cli
    
    - name: Deploy
      run: |
        cd hexo
        npm i
        hexo clean
        hexo g
        hexo d
